### ISSUE TITLE
Error on build on /LocaleBasedValueConverter.kt: (23, 29)

### ISSUE THREAD

**Issue by ppazos** [better-care/web-template#1]
$ mvn clean install

[ERROR] /home/pab/GitHub/web-template/src/main/kotlin/care/better/platform/web/template/converter/value/LocaleBasedValueConverter.kt: (23, 29) Unresolved reference: ws

**Comment by ppazos** [comment]
Actually the offending line was introduced by this commit https://github.com/better-care/web-template/commit/9ea163d73f83e1e7bc87e18a6257ce65417e70cc#diff-963031ba4ad0c2a8128aedc425607c9c53970f4af53fbe3d65c9cbb6b63e2e7dR23

But the referenced class was not used at all. Removed that line and the build continues, though there are many errors in the test execution about classes that were not found:

```
[ERROR] testSecondDateTime  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testMultimedia  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testFirstDate  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testFirstTime  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testProportionWithInvalidDenominator  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testFirstDateTime  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testMultimediaFailedInvalidValue  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testMultimediaUnknownAttribute  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[INFO] Running care.better.platform.web.template.converter.LocalizationTest
[ERROR] Tests run: 13, Failures: 0, Errors: 13, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in care.better.platform.web.template.converter.LocalizationTest
[ERROR] testAnnotations  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testInvalidNode  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testInvalidPath  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testEmptyDefaultLanguage  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testSecoondCodes  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testCodes  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testUnits  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testConstrainedNameLocalization  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testSecondUnits  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testAnnotationsV2  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testPerinatal  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testAnnotationsFromAD  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testLabels  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[INFO] Running care.better.platform.web.template.FindNodeTest
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in care.better.platform.web.template.FindNodeTest
[ERROR] testFindNodeById  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
[ERROR] testFindNodeByAqlPathRelative  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
[ERROR] testFindNodeByAqlPath  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
[ERROR] testCdaDocument  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
[ERROR] testFindNodeByIdNonExisting  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
```

**Comment by ppazos** [comment]
The missing class seems to be in the ehr-common project, which is in version 3.1.0-SNAPSHOT

https://github.com/better-care/ehr-common/blob/master/pom.xml#L32

The dependency from web-template is 3.1.0-RC1, I tried to change it to SNAPSHOT, and the dependency is not found.

If seems there is an issue finding the right version of ehr-common with the JaxbRegistry class.

**Comment by delopst** [comment]
Hi. 

Do you have the latest files of the master branch locally? 

Currently, the latest released version of the ehr-common is 3.1.0-RC1  (this version is currently used in web-template project).

I have tried this locally and in circle-ci and everything is working.
Which version of Java are you using?

Regards, Primoz

**Comment by ppazos** [comment]
Hi @delopst 

This machine has:

```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode)
```


It's the latest code, I just did a clone of master.

**Comment by delopst** [comment]
Currently web-template library only supports Java 8. We are planning to add support for the higher Java versions shortly (this or the next week).

Cn you use Java 8 for now?

Regards, Primoz

**Comment by ppazos** [comment]
I have tried:

```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode)
```

These tests failed:

[ERROR] testSecondDateTime  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testMultimedia  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testFirstDate  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testFirstTime  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testProportionWithInvalidDenominator  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testFirstDateTime  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testMultimediaFailedInvalidValue  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[ERROR] testMultimediaUnknownAttribute  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.RmObjectLeafNodeFactoriesTest.<init>(RmObjectLeafNodeFactoriesTest.kt:51)
[INFO] Running care.better.platform.web.template.converter.LocalizationTest
[ERROR] Tests run: 13, Failures: 0, Errors: 13, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in care.better.platform.web.template.converter.LocalizationTest
[ERROR] testAnnotations  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testInvalidNode  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testInvalidPath  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testEmptyDefaultLanguage  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testSecoondCodes  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testCodes  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testUnits  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testConstrainedNameLocalization  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testSecondUnits  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testAnnotationsV2  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testPerinatal  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testAnnotationsFromAD  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[ERROR] testLabels  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.converter.LocalizationTest.<init>(LocalizationTest.kt:37)
[INFO] Running care.better.platform.web.template.FindNodeTest
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in care.better.platform.web.template.FindNodeTest
[ERROR] testFindNodeById  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
[ERROR] testFindNodeByAqlPathRelative  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
[ERROR] testFindNodeByAqlPath  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
[ERROR] testCdaDocument  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)
[ERROR] testFindNodeByIdNonExisting  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class care.better.platform.jaxb.JaxbRegistry
	at care.better.platform.web.template.FindNodeTest.<init>(FindNodeTest.kt:33)

**Comment by bratwurzt** [comment]
Fixed with commit 0a46ba2ca6cff5088b59b98bd0562ac269352760

**Comment by ppazos** [comment]
@bratwurzt thanks, it seems there are 2 more tests passing but still 5 tests failing and not building:

If you check the tests about the dates, the issue is my timezone is different than yours, and it seems to compare hardcoded dates with timezone, which might be generated for the local TZ. My TZ is -0300.

[ERROR] Failures:
[ERROR]   PartialTemporalTest.testDateTimeAny:95->assertValueMatches$default:280->assertValueMatches:287
Expecting:
 <2019-02-01T13:10:20.777+01:00 (java.time.OffsetDateTime)>
to be equal to:
 <2019-02-01T13:10:20.777-03:00 (java.time.OffsetDateTime)>
but was not.
[ERROR]   PartialTemporalTest.testDateTimeFull:167->assertValueMatches$default:280->assertValueMatches:287
Expecting:
 <2019-02-01T13:10:20.777+01:00 (java.time.OffsetDateTime)>
to be equal to:
 <2019-02-01T13:10:20.777-03:00 (java.time.OffsetDateTime)>
but was not.
[ERROR]   PartialTemporalTest.testDateTimePartial:205->assertValueMatches$default:280->assertValueMatches:287
Expecting:
 <2019-02-01T13:10:20.777+01:00 (java.time.OffsetDateTime)>
to be equal to:
 <2019-02-01T13:10:20.777-03:00 (java.time.OffsetDateTime)>
but was not.
[ERROR]   RmObjectLeafNodeFactoriesTest.testFirstTime:282
Expecting map:
 <{"testing_template/category|code"="433", "testing_template/category|terminology"="openehr", "testing_template/category|value"="event", "testing_template/composer|name"="composer", "testing_template/context/setting|code"="238", "testing_template/context/setting|terminology"="openehr", "testing_template/context/setting|value"="other care", "testing_template/context/start_time"="2021-08-19T14:16:14.196-03:00", "testing_template/context/testing/time"="14:35:10.117-02:00", "testing_template/language|code"="sl", "testing_template/language|terminology"="ISO_639-1", "testing_template/territory|code"="SL", "testing_template/territory|terminology"="ISO_3166-1"}>
to contain:
 <[MapEntry[key="testing_template/context/testing/time", value="14:35:10.117+01:00"]]>
but could not find the following map entries:
 <[MapEntry[key="testing_template/context/testing/time", value="14:35:10.117+01:00"]]>
[ERROR]   RmObjectLeafNodeFactoriesTest.testThirdTime:329
Expecting map:
 <{"testing_template/category|code"="433", "testing_template/category|terminology"="openehr", "testing_template/category|value"="event", "testing_template/composer|name"="composer", "testing_template/context/setting|code"="238", "testing_template/context/setting|terminology"="openehr", "testing_template/context/setting|value"="other care", "testing_template/context/start_time"="2021-08-19T14:16:13.977-03:00", "testing_template/context/testing/time"="14:35:10.117-02:00", "testing_template/language|code"="sl", "testing_template/language|terminology"="ISO_639-1", "testing_template/territory|code"="SL", "testing_template/territory|terminology"="ISO_3166-1"}>
to contain:
 <[MapEntry[key="testing_template/context/testing/time", value="14:35:10.117+01:00"]]>
but could not find the following map entries:
 <[MapEntry[key="testing_template/context/testing/time", value="14:35:10.117+01:00"]]>
[ERROR] Errors:
[ERROR]   ClinicalTest.testPerinatal:297 » Conversion Unable to convert value to DateTim...
[ERROR]   ClinicalTest.testSecondVitalsSingle:202 » Conversion Unable to convert value t...
[ERROR]   ClinicalTest.testVitalsSingle:106 » Conversion Unable to convert value to Date...
[ERROR]   ValueConverterTest.testGerman:49 » Conversion Unable to convert value to DateT...
[ERROR]   ValueConverterTest.testRussian:37 » Conversion Unable to convert value to Date...
[INFO]
[ERROR] Tests run: 474, Failures: 5, Errors: 5, Skipped: 0

**Comment by bratwurzt** [comment]
Hi @ppazos, ZoneId for ZonedDateTime creation is now hardcoded.

**Comment by ppazos** [comment]
Yes, that's the issue, the tests pass or fall depending on were you are. I'll just remove the tests for it to build, thanks.

**Comment by bratwurzt** [comment]
Hi @ppazos, could you try again? I had to force push the changes so I'd recommend re-cloning the repo.
